//! RFC-3161 trusted-time anchoring — the VERIFY side (always on, fail-closed)
//! and a feature-gated producer.
//!
//! A [`crate::receipt::TimeAnchor`] is an independent "existed-no-later-than"
//! bound over a receipt's `action_hash`: a TSA (Time-Stamping Authority) signs a
//! token attesting it saw that hash at a given time. `captured_at` is the
//! operator's own clock and is NOT trusted; the anchor is the non-operator
//! countersignature that is.
//!
//! ## Two layers, one contract
//!
//! [`verify_time_anchor`] is the entry point the verifier calls. It is ALWAYS
//! compiled and ALWAYS fails closed:
//!
//! - **Always-on preconditions** (no crypto deps): the anchor `kind` must be
//!   [`TIME_ANCHOR_RFC3161`], `anchored_hash` must be 64-lowercase-hex AND equal
//!   the receipt's recomputed `action_hash`, and `token_b64` must be non-empty
//!   valid base64. These catch the cheap forgeries with zero dependencies.
//! - **Cryptographic verification** of the CMS `SignedData` / `TSTInfo`
//!   (parsing the DER token, checking its `messageImprint` is `action_hash`,
//!   verifying the TSA signature, chaining the TSA cert to a **pinned in-binary
//!   root**, and requiring the `id-kp-timeStamping` EKU) is compiled ONLY under
//!   the `tsa` cargo feature, which pulls the RustCrypto ASN.1 stack.
//!
//! With the `tsa` feature OFF, a *present* anchor that passes the preconditions
//! cannot be cryptographically checked — so it FAILS CLOSED
//! ([`Err`] → [`crate::verify::ActionOutcome::TimeAnchorUnverifiable`]) rather
//! than being vouched for. The default zero-dep build therefore never asserts
//! trusted time it cannot prove; turning on `tsa` is what lets a present anchor
//! verify to `Ok`.
//!
//! ## Pinned TSA roots
//!
//! Trust is anchored to a small set of roots compiled into the binary
//! ([`PINNED_TSA_ROOTS`]), never to the `tsa` string in the anchor (which is
//! informational). This is the same "pin the verifier's trust, don't take it
//! from the artifact" discipline the rest of HESO uses.

use crate::domain::TIME_ANCHOR_RFC3161;
use crate::receipt::TimeAnchor;
use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine as _;

// The DER bytes of the TSA root certificates this verifier trusts, pinned into
// the binary as `pub static PINNED_TSA_ROOTS: &[&[u8]]`. Trust is decided against
// THESE, never against the anchor's `tsa` string.
//
// Under the `tsa` feature this is generated by `build.rs` from `roots/*.der` +
// `roots/roots.toml`: each root is parsed as X.509 and its SHA-256 is asserted
// equal to the manifest pin AT COMPILE TIME (the build fails on drift). The set
// currently pins DigiCert Trusted Root G4, DigiCert Assured ID Root CA, and the
// Free TSA root. With the feature OFF there is no crypto stack to chain with, so
// the slice is EMPTY (below) — no placeholder bytes are ever embedded.
//
// The `pinned_root_count` accessor lets the always-on layer and tests assert the
// pin set without depending on the `tsa` crypto stack; the actual chaining
// against these only runs under the `tsa` feature.
#[cfg(feature = "tsa")]
include!(concat!(env!("OUT_DIR"), "/pinned_tsa_roots.rs"));

/// With the `tsa` feature OFF there is no verifier and therefore no trust set.
#[cfg(not(feature = "tsa"))]
pub static PINNED_TSA_ROOTS: &[&[u8]] = &[];

/// Number of pinned TSA roots — surfaced so the always-on layer and tests can
/// assert the pin set is present without parsing certificates.
pub fn pinned_root_count() -> usize {
    PINNED_TSA_ROOTS.len()
}

/// Verify a present [`TimeAnchor`] against the receipt's `action_hash`.
///
/// Returns `Ok(gen_time)` (the TSA-asserted RFC-3161 `genTime`, empty when the
/// `tsa` feature did not extract it) when the anchor is trustworthy, or
/// `Err(reason)` — FAIL CLOSED — on any problem. The caller
/// ([`crate::verify::open_receipt`]) maps `Err` to
/// [`crate::verify::ActionOutcome::TimeAnchorUnverifiable`].
///
/// `action_hash` MUST already be the verifier's recomputed self-hash (verify
/// checks the hash before this runs), so binding the anchor to it binds it to the
/// authenticated content.
pub fn verify_time_anchor(anchor: &TimeAnchor, action_hash: &str) -> Result<String, String> {
    // --- Always-on preconditions (no crypto deps) ---------------------------
    if anchor.kind != TIME_ANCHOR_RFC3161 {
        return Err(format!(
            "time_anchor kind `{}` is not supported (expected `{TIME_ANCHOR_RFC3161}`)",
            anchor.kind
        ));
    }
    if !is_64_lower_hex(&anchor.anchored_hash) {
        return Err("time_anchor anchored_hash is not 64 lowercase-hex".to_string());
    }
    // The anchor must be over THIS receipt's authenticated hash — not some other.
    if anchor.anchored_hash != action_hash {
        return Err(format!(
            "time_anchor anchored_hash {} does not match action_hash {action_hash}",
            anchor.anchored_hash
        ));
    }
    let token = B64
        .decode(anchor.token_b64.as_bytes())
        .map_err(|_| "time_anchor token_b64 is not valid base64".to_string())?;
    if token.is_empty() {
        return Err("time_anchor token_b64 decoded to empty".to_string());
    }

    // --- Cryptographic verification (feature-gated) -------------------------
    verify_token_crypto(&token, action_hash)
}

/// 64 lowercase-hex predicate (shared with the redaction check's discipline).
fn is_64_lower_hex(s: &str) -> bool {
    s.len() == 64 && s.chars().all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase())
}

// ============================================================================
// Cryptographic verification — feature-gated
// ============================================================================

/// With the `tsa` feature OFF: a present, precondition-passing anchor still
/// cannot be cryptographically checked, so it FAILS CLOSED. The default build
/// never vouches for trusted time it cannot verify.
#[cfg(not(feature = "tsa"))]
fn verify_token_crypto(_token: &[u8], _action_hash: &str) -> Result<String, String> {
    Err("time_anchor present but RFC-3161 verification is unavailable in this build \
         (rebuild heso-action with the `tsa` feature); failing closed"
        .to_string())
}

/// With the `tsa` feature ON: parse the DER CMS `SignedData`, confirm its
/// `TSTInfo.messageImprint` is `action_hash`, verify the TSA signature, chain the
/// signer cert to a pinned root, and require the `id-kp-timeStamping` EKU.
///
/// Returns the TSA `genTime` on success. This is the REAL verify path; it is
/// gated only because it pulls the RustCrypto ASN.1 stack (`cms`/`x509-cert`/
/// `der`/`rsa`/`sha2`), which heso-action keeps out of its zero-dep default.
#[cfg(feature = "tsa")]
fn verify_token_crypto(token: &[u8], action_hash: &str) -> Result<String, String> {
    tsa_crypto::verify(token, action_hash, PINNED_TSA_ROOTS)
}

/// The real RFC-3161 verifier, compiled only under the `tsa` feature.
#[cfg(feature = "tsa")]
mod tsa_crypto {
    use cms::content_info::ContentInfo;
    use cms::signed_data::{SignedData, SignerIdentifier, SignerInfo};
    use const_oid::db::rfc5280::ID_KP_TIME_STAMPING;
    use const_oid::ObjectIdentifier;
    use der::asn1::{GeneralizedTime, OctetString};
    use der::{Decode, DecodeValue, Encode, FixedTag, Header, Reader, Sequence, Tag};
    use x509_cert::spki::AlgorithmIdentifierOwned;
    use x509_cert::Certificate;

    /// OID for `id-ct-TSTInfo` (1.2.840.113549.1.9.16.1.4) — the CMS
    /// eContentType of an RFC-3161 timestamp token.
    const ID_CT_TST_INFO: &str = "1.2.840.113549.1.9.16.1.4";

    /// OID for the `message-digest` signed attribute (PKCS#9, 1.2.840.113549.1.9.4).
    const ID_MESSAGE_DIGEST: ObjectIdentifier =
        ObjectIdentifier::new_unwrap("1.2.840.113549.1.9.4");

    /// OID for `id-sha256` (2.16.840.1.101.3.4.2.1) — the
    /// `messageImprint.hashAlgorithm` HESO mints its tokens under.
    ///
    /// No public RFC-3161 TSA will sign a BLAKE3 imprint, so HESO anchors the
    /// SHA-256 *of the 32 raw BLAKE3 `action_hash` bytes*. This is NOT a
    /// weakening: the SHA-256 pre-image IS the already-authenticated
    /// `action_hash`, so the imprint binds 1:1 to it — `SHA-256(action_hash)`
    /// can only be produced from that exact hash. The verifier PINS this OID: a
    /// token whose imprint algorithm is anything else is refused.
    const ID_SHA256_OID: ObjectIdentifier =
        ObjectIdentifier::new_unwrap("2.16.840.1.101.3.4.2.1");

    /// `RFC-3161 MessageImprint ::= SEQUENCE { hashAlgorithm AlgorithmIdentifier,
    /// hashedMessage OCTET STRING }`.
    #[derive(Clone, Debug, Eq, PartialEq, Sequence)]
    struct MessageImprint {
        hash_algorithm: AlgorithmIdentifierOwned,
        hashed_message: OctetString,
    }

    /// A minimal `RFC-3161 TSTInfo` decoder — enough to read the messageImprint
    /// and genTime, the only fields the verifier trusts and keys on.
    ///
    /// `TSTInfo` is a SEQUENCE whose first five fields (version, policy,
    /// messageImprint, serialNumber, genTime) are required, followed by the
    /// OPTIONAL `accuracy`, `ordering` (DEFAULT FALSE), `nonce`, `[0] tsa` and
    /// `[1] extensions`. Every real public TSA emits some of those trailing
    /// fields. We therefore decode the required prefix and then DRAIN the rest:
    /// each remaining TLV is consumed and discarded so the SEQUENCE body is fully
    /// read. A `der::Sequence` derive cannot do this — it requires the whole body
    /// to map onto declared fields and fails as "trailing data" — so we implement
    /// `DecodeValue` by hand. Draining still parses the TLV framing (length-checked
    /// by the reader), so a truncated or malformed trailing field fails closed; we
    /// simply do not interpret fields we place no trust in.
    #[derive(Clone, Debug, Eq, PartialEq)]
    struct TstInfo {
        message_imprint: MessageImprint,
        gen_time: GeneralizedTime,
    }

    impl FixedTag for TstInfo {
        const TAG: Tag = Tag::Sequence;
    }

    impl<'a> DecodeValue<'a> for TstInfo {
        type Error = der::Error;

        fn decode_value<R: Reader<'a>>(reader: &mut R, _header: Header) -> der::Result<Self> {
            // version + policy precede the messageImprint; drain them by TLV
            // framing (we key on neither, and policy is a `MAX_SIZE`-generic OID
            // that does not infer in a bare `decode`).
            reader.tlv_bytes()?; // version
            reader.tlv_bytes()?; // policy
            let message_imprint = MessageImprint::decode(reader)?;
            let _serial_number = der::asn1::Int::decode(reader)?;
            let gen_time = GeneralizedTime::decode(reader)?;
            // Drain the trailing OPTIONAL fields (accuracy/ordering/nonce/tsa/
            // extensions). `tlv_bytes` reads one full TLV and advances the reader;
            // when the body is exhausted the blanket `Decode` impl's `finish()`
            // sees no leftover and succeeds.
            while !reader.is_finished() {
                reader.tlv_bytes()?;
            }
            Ok(Self { message_imprint, gen_time })
        }
    }

    /// Verify a DER RFC-3161 token. See [`super::verify_token_crypto`].
    pub fn verify(token: &[u8], action_hash: &str, roots: &[&[u8]]) -> Result<String, String> {
        // 1. Parse the outer CMS ContentInfo → SignedData.
        let ci = ContentInfo::from_der(token)
            .map_err(|e| format!("RFC-3161 token is not valid CMS ContentInfo: {e}"))?;
        let sd = ci
            .content
            .decode_as::<SignedData>()
            .map_err(|e| format!("CMS content is not SignedData: {e}"))?;

        // 2. The eContentType must be id-ct-TSTInfo and carry the TSTInfo bytes.
        let econtent = sd
            .encap_content_info
            .econtent
            .as_ref()
            .ok_or_else(|| "SignedData has no eContent (detached TSTInfo unsupported)".to_string())?;
        if sd.encap_content_info.econtent_type.to_string() != ID_CT_TST_INFO {
            return Err(format!(
                "eContentType {} is not id-ct-TSTInfo",
                sd.encap_content_info.econtent_type
            ));
        }
        let tst_info_der = econtent
            .value()
            .to_vec();

        // 3. The TSTInfo.messageImprint hashedMessage must be SHA-256(action_hash).
        //    We keep the parsed genTime to window cert validity offline.
        let (gen_time_display, gen_time) = check_message_imprint(&tst_info_der, action_hash)?;

        // 4. Find the signer certificate (by SignerInfo sid), require the
        //    timeStamping EKU, and build a bounded path from it through any
        //    embedded intermediates to a pinned root, validating each cert's
        //    validity window against the token's OWN genTime (never wall-clock).
        let signer_cert = signer_certificate(&sd)?;
        require_timestamping_eku(&signer_cert)?;
        chain_to_pinned_root(&signer_cert, &sd, roots, &gen_time)?;

        // 5. Verify the TSA signature over the SignedAttributes (RSA/ECDSA).
        verify_signer_signature(&sd, &signer_cert)?;

        Ok(gen_time_display)
    }

    /// Decode TSTInfo far enough to read messageImprint.hashedMessage and
    /// genTime; confirm the imprint equals `SHA-256(action_hash_bytes)` — the
    /// SHA-256 of the 32 raw BLAKE3 bytes of the receipt's `action_hash`.
    ///
    /// Returns `(gen_time_display, gen_time)` so callers that need the parsed
    /// `GeneralizedTime` for cert-validity windowing get it without re-parsing.
    fn check_message_imprint(
        tst_info_der: &[u8],
        action_hash: &str,
    ) -> Result<(String, GeneralizedTime), String> {
        use sha2::Digest;

        let tst = TstInfo::from_der(tst_info_der)
            .map_err(|e| format!("TSTInfo is not valid DER: {e}"))?;

        // PIN the imprint hash algorithm to id-sha256. No public RFC-3161 TSA
        // signs a BLAKE3 imprint; HESO anchors SHA-256 OVER the raw BLAKE3
        // action_hash bytes. A token whose imprint algorithm is anything else is
        // refused, so a token minted over a different digest cannot ride along.
        if tst.message_imprint.hash_algorithm.oid != ID_SHA256_OID {
            return Err(format!(
                "messageImprint hashAlgorithm {} is not the expected id-sha256 OID {ID_SHA256_OID}",
                tst.message_imprint.hash_algorithm.oid
            ));
        }

        // The anchored hash is a 64-hex BLAKE3 digest (32 raw bytes). The imprint
        // commits to SHA-256(those 32 bytes) — which binds 1:1 to the
        // authenticated action_hash (only that hash produces this imprint).
        let raw = hex_to_32(action_hash)
            .ok_or_else(|| "action_hash is not 64-hex (32 bytes)".to_string())?;
        let want = sha2::Sha256::digest(raw);
        if tst.message_imprint.hashed_message.as_bytes() != want.as_slice() {
            return Err(
                "messageImprint hashedMessage does not equal SHA-256(action_hash)".to_string(),
            );
        }

        // The TSA-asserted genTime, rendered as an RFC3339-ish string for display,
        // plus the parsed value for cert-validity windowing.
        Ok((tst.gen_time.to_date_time().to_string(), tst.gen_time))
    }

    /// Decode a 64-char lowercase-hex string into 32 raw bytes, or `None` if it is
    /// not exactly 64 hex chars.
    fn hex_to_32(s: &str) -> Option<[u8; 32]> {
        if s.len() != 64 {
            return None;
        }
        let mut out = [0u8; 32];
        let bytes = s.as_bytes();
        for (i, slot) in out.iter_mut().enumerate() {
            let hi = (bytes[2 * i] as char).to_digit(16)?;
            let lo = (bytes[2 * i + 1] as char).to_digit(16)?;
            *slot = (hi * 16 + lo) as u8;
        }
        Some(out)
    }

    /// Collect every embedded X.509 certificate from the SignedData. These are
    /// UNTRUSTED path material: the leaf signer plus any intermediates a real TSA
    /// token bundles. Trust comes only from chaining up to a pinned root.
    fn collect_certificates(sd: &SignedData) -> Result<Vec<Certificate>, String> {
        let certs = sd
            .certificates
            .as_ref()
            .ok_or_else(|| "SignedData carries no certificates".to_string())?;
        let mut out = Vec::new();
        for cert_choice in certs.0.iter() {
            if let cms::cert::CertificateChoices::Certificate(c) = cert_choice {
                out.push(c.clone());
            }
        }
        if out.is_empty() {
            return Err("SignedData has no X.509 certificate".to_string());
        }
        Ok(out)
    }

    /// Pick the LEAF signer certificate, matching the (single) SignerInfo's `sid`
    /// against the embedded certs. We support the `IssuerAndSerialNumber` sid form
    /// (what RFC-3161 tokens use); `SubjectKeyIdentifier` is unsupported (fail
    /// closed). Selecting by sid (not "the first cert") means a token that lists
    /// the chain in any order, or includes the responder among intermediates, is
    /// still bound to the cert that actually signed.
    fn signer_certificate(sd: &SignedData) -> Result<Certificate, String> {
        let signer_info: &SignerInfo = sd
            .signer_infos
            .0
            .as_slice()
            .first()
            .ok_or_else(|| "SignedData carries no SignerInfo".to_string())?;
        let certs = collect_certificates(sd)?;

        match &signer_info.sid {
            SignerIdentifier::IssuerAndSerialNumber(ias) => {
                for c in &certs {
                    let tbs = c.tbs_certificate();
                    if tbs.issuer() == &ias.issuer && tbs.serial_number() == &ias.serial_number {
                        return Ok(c.clone());
                    }
                }
                Err("no embedded certificate matches the SignerInfo issuer+serial".to_string())
            }
            SignerIdentifier::SubjectKeyIdentifier(_) => {
                Err("SignerInfo sid uses SubjectKeyIdentifier (unsupported); failing closed"
                    .to_string())
            }
        }
    }

    fn require_timestamping_eku(cert: &Certificate) -> Result<(), String> {
        let exts = cert
            .tbs_certificate()
            .extensions()
            .ok_or_else(|| "TSA certificate has no extensions".to_string())?;
        for ext in exts.iter() {
            if ext.extn_id == const_oid::db::rfc5280::ID_CE_EXT_KEY_USAGE {
                use x509_cert::ext::pkix::ExtendedKeyUsage;
                let eku = ExtendedKeyUsage::from_der(ext.extn_value.as_bytes())
                    .map_err(|e| format!("malformed EKU extension: {e}"))?;
                if eku.0.contains(&ID_KP_TIME_STAMPING) {
                    return Ok(());
                }
                return Err("TSA certificate EKU lacks id-kp-timeStamping".to_string());
            }
        }
        Err("TSA certificate has no Extended Key Usage extension".to_string())
    }

    /// Max certificates in a path (leaf + intermediates + root). RFC-3161 TSA
    /// tokens are shallow (DigiCert is leaf→intermediate→root); 4 leaves headroom
    /// while bounding work and refusing pathological/looping inputs.
    const MAX_CHAIN_DEPTH: usize = 4;

    /// Build a bounded path from the leaf signer cert, walking issuer-by-name
    /// through any embedded intermediates, to a PINNED root. Every cert on the
    /// path is validated:
    ///
    /// - its `notBefore <= genTime <= notAfter` window contains the token's OWN
    ///   `genTime` (NEVER wall-clock — verification stays offline + deterministic),
    /// - each hop's signature verifies under its issuer's key (name binding alone
    ///   is never trusted), RSA or ECDSA.
    ///
    /// Depth is capped at [`MAX_CHAIN_DEPTH`] and a visited-set rejects cycles.
    /// Terminates ONLY when a cert is issued by (and signature-verifies under) a
    /// pinned root; anything else fails closed.
    fn chain_to_pinned_root(
        leaf: &Certificate,
        sd: &SignedData,
        roots: &[&[u8]],
        gen_time: &GeneralizedTime,
    ) -> Result<(), String> {
        // Parse the pinned roots once. An unparseable pin is not a trust anchor.
        let pinned: Vec<Certificate> = roots
            .iter()
            .filter_map(|r| Certificate::from_der(r).ok())
            .collect();
        if pinned.is_empty() {
            return Err("no parseable pinned TSA root configured; failing closed".to_string());
        }

        let intermediates = collect_certificates(sd)?;

        // Walk: current cert -> issuer. At each step, first try to terminate at a
        // pinned root; else find an embedded intermediate whose subject matches the
        // current issuer and continue. Validity-window + signature checked per hop.
        let mut current = leaf.clone();
        let mut visited: Vec<Vec<u8>> = Vec::new();

        for _depth in 0..MAX_CHAIN_DEPTH {
            // Reject cycles: a cert (by its DER) may appear at most once on a path.
            let cur_der = current
                .to_der()
                .map_err(|e| format!("re-encoding cert on path failed: {e}"))?;
            if visited.iter().any(|v| v == &cur_der) {
                return Err("certificate path contains a cycle; failing closed".to_string());
            }
            visited.push(cur_der);

            // The current cert must itself be valid at genTime.
            check_validity_window(&current, gen_time)?;

            // (a) Try to terminate: is `current` issued by a pinned root?
            for root in &pinned {
                if current.tbs_certificate().issuer() != root.tbs_certificate().subject() {
                    continue;
                }
                // The pinned root must also be valid at genTime, and must actually
                // have signed `current`.
                check_validity_window(root, gen_time)?;
                if verify_cert_signed_by(&current, root).is_ok() {
                    return Ok(());
                }
            }

            // (b) Otherwise step to an embedded intermediate that issued `current`.
            let issuer_name = current.tbs_certificate().issuer().clone();
            let next = intermediates.iter().find(|cand| {
                // The candidate's subject must be the current issuer, it must not be
                // `current` itself (self-issued non-root would loop), and it must
                // have actually signed `current`.
                cand.tbs_certificate().subject() == &issuer_name
                    && cand.tbs_certificate().subject() != current.tbs_certificate().subject()
                    && verify_cert_signed_by(&current, cand).is_ok()
            });

            match next {
                Some(parent) => current = parent.clone(),
                None => {
                    return Err(
                        "TSA cert path does not reach any pinned root (no issuer found / \
                         signature mismatch); failing closed"
                            .to_string(),
                    );
                }
            }
        }

        Err(format!(
            "TSA cert path exceeded max depth {MAX_CHAIN_DEPTH} without reaching a pinned root; \
             failing closed"
        ))
    }

    /// Validate `cert`'s `notBefore <= genTime <= notAfter` window using the
    /// token's OWN genTime. This keeps verification fully offline and
    /// deterministic — we never consult the wall clock.
    fn check_validity_window(cert: &Certificate, gen_time: &GeneralizedTime) -> Result<(), String> {
        let validity = cert.tbs_certificate().validity();
        let not_before = validity.not_before.to_unix_duration();
        let not_after = validity.not_after.to_unix_duration();
        let at = gen_time.to_unix_duration();
        if at < not_before {
            return Err("a certificate on the path is not yet valid at the token genTime".to_string());
        }
        if at > not_after {
            return Err("a certificate on the path is expired at the token genTime".to_string());
        }
        Ok(())
    }

    /// Verify `cert`'s signature was produced by `issuer`'s public key. RSA
    /// PKCS#1 v1.5 OR ECDSA (P-256/P-384) over the re-encoded TBSCertificate,
    /// dispatched on `cert`'s `signatureAlgorithm`.
    fn verify_cert_signed_by(cert: &Certificate, issuer: &Certificate) -> Result<(), String> {
        let tbs_der = cert
            .tbs_certificate()
            .to_der()
            .map_err(|e| format!("re-encoding TBSCertificate failed: {e}"))?;
        let sig = cert
            .signature()
            .as_bytes()
            .ok_or_else(|| "certificate signature is not a whole number of bytes".to_string())?;
        let spki = issuer.tbs_certificate().subject_public_key_info();
        // A certificate always names the full hash-and-key algorithm (e.g.
        // sha256WithRSAEncryption), so there is no separate digest OID to resolve.
        verify_signature(&cert.signature_algorithm().oid, None, spki, &tbs_der, sig)
    }

    fn verify_signer_signature(sd: &SignedData, cert: &Certificate) -> Result<(), String> {
        let signer_info: &SignerInfo = sd
            .signer_infos
            .0
            .as_slice()
            .first()
            .ok_or_else(|| "SignedData carries no SignerInfo".to_string())?;

        // The eContent (the TSTInfo bytes) the signature commits to.
        let econtent = sd
            .encap_content_info
            .econtent
            .as_ref()
            .ok_or_else(|| "SignedData has no eContent".to_string())?;
        let econtent_value = econtent.value();

        let signed_message = match signer_info.signed_attrs.as_ref() {
            // CMS with signed attributes: the `message-digest` attribute MUST equal
            // digest(eContent), and the signature is over the DER of the SET OF
            // signed attributes (re-tagged from the IMPLICIT [0] to the SET tag).
            Some(signed_attrs) => {
                let want_digest = digest_for(&signer_info.digest_alg.oid, econtent_value)
                    .ok_or_else(|| "unsupported SignerInfo digestAlgorithm".to_string())?;
                let md = message_digest_attr(signed_attrs)
                    .ok_or_else(|| "SignerInfo signed attrs lack a message-digest".to_string())?;
                if md != want_digest.as_slice() {
                    return Err(
                        "SignerInfo message-digest attr does not equal digest(eContent)".to_string(),
                    );
                }
                // Re-encode the signed attrs under the SET OF tag (DER), which is
                // what RFC 5652 §5.4 says is signed (not the IMPLICIT [0] form).
                signed_attrs
                    .to_der()
                    .map_err(|e| format!("re-encoding signed attrs failed: {e}"))?
            }
            // No signed attributes: the eContent itself is the signed message.
            None => econtent_value.to_vec(),
        };

        let sig = signer_info.signature.as_bytes();
        let spki = cert.tbs_certificate().subject_public_key_info();
        // Some TSAs (e.g. DigiCert) label the SignerInfo signatureAlgorithm with the
        // bare `rsaEncryption` OID and name the hash only in `digestAlgorithm`. Pass
        // the SignerInfo digest OID so `verify_signature` can resolve the hash in
        // that case.
        verify_signature(
            &signer_info.signature_algorithm.oid,
            Some(&signer_info.digest_alg.oid),
            spki,
            &signed_message,
            sig,
        )
    }

    /// Extract the `message-digest` signed attribute's OCTET STRING value.
    fn message_digest_attr(attrs: &cms::signed_data::SignedAttributes) -> Option<Vec<u8>> {
        for attr in attrs.iter() {
            if attr.oid == ID_MESSAGE_DIGEST {
                let any = attr.values.as_slice().first()?;
                let octets = any.decode_as::<OctetString>().ok()?;
                return Some(octets.as_bytes().to_vec());
            }
        }
        None
    }

    /// Digest `data` under the SignerInfo digest-algorithm OID (SHA-256/384/512).
    fn digest_for(oid: &ObjectIdentifier, data: &[u8]) -> Option<Vec<u8>> {
        use sha2::Digest;
        match oid.to_string().as_str() {
            // id-sha256
            "2.16.840.1.101.3.4.2.1" => Some(sha2::Sha256::digest(data).to_vec()),
            // id-sha384
            "2.16.840.1.101.3.4.2.2" => Some(sha2::Sha384::digest(data).to_vec()),
            // id-sha512
            "2.16.840.1.101.3.4.2.3" => Some(sha2::Sha512::digest(data).to_vec()),
            _ => None,
        }
    }

    /// id-sha256 / id-sha384 / id-sha512 OIDs — the SignerInfo `digestAlgorithm`
    /// names the hash here when the signatureAlgorithm is the bare `rsaEncryption`.
    const ID_SHA256_DIGEST: &str = "2.16.840.1.101.3.4.2.1";
    const ID_SHA384_DIGEST: &str = "2.16.840.1.101.3.4.2.2";
    const ID_SHA512_DIGEST: &str = "2.16.840.1.101.3.4.2.3";

    /// Verify a certificate/SignerInfo signature over `message` under the public
    /// key in `spki`, dispatching on the signature-algorithm OID.
    ///
    /// Supported:
    /// - RSA PKCS#1 v1.5 under `sha{256,384,512}WithRSAEncryption`, AND under the
    ///   bare `rsaEncryption` OID (1.2.840.113549.1.1.1) — which some TSAs
    ///   (DigiCert) use on the SignerInfo, naming the hash only in the SignerInfo
    ///   `digestAlgorithm`. `digest_oid` carries that hash for the bare case.
    /// - ECDSA under `ecdsa-with-SHA{256,384,512}`. The CURVE comes from the SPKI
    ///   (P-256 or P-384), the HASH from the OID; both are honoured independently
    ///   (e.g. freeTSA signs P-384 keys with SHA-512). Verification is done over an
    ///   explicit prehash so the hash is never silently taken from the curve.
    ///
    /// An unknown OID, an SPKI that is the wrong key type, a hash we cannot resolve,
    /// or a bad signature all fail closed.
    fn verify_signature(
        sig_alg_oid: &ObjectIdentifier,
        digest_oid: Option<&ObjectIdentifier>,
        spki: &x509_cert::spki::SubjectPublicKeyInfoOwned,
        message: &[u8],
        signature: &[u8],
    ) -> Result<(), String> {
        use sha2::Digest;
        let spki_der = spki.to_der().map_err(|e| format!("re-encoding SPKI failed: {e}"))?;

        let ok = match sig_alg_oid.to_string().as_str() {
            // --- RSA PKCS#1 v1.5 -------------------------------------------------
            // sha256WithRSAEncryption / sha384 / sha512: hash named by the OID.
            "1.2.840.113549.1.1.11" => verify_rsa::<sha2::Sha256>(&spki_der, message, signature)?,
            "1.2.840.113549.1.1.12" => verify_rsa::<sha2::Sha384>(&spki_der, message, signature)?,
            "1.2.840.113549.1.1.13" => verify_rsa::<sha2::Sha512>(&spki_der, message, signature)?,
            // rsaEncryption: the signatureAlgorithm does NOT name a hash, so resolve
            // it from the SignerInfo digestAlgorithm (RFC 5652 / RFC 8933).
            "1.2.840.113549.1.1.1" => {
                let digest_oid = digest_oid.ok_or_else(|| {
                    "rsaEncryption signature with no digestAlgorithm to resolve the hash".to_string()
                })?;
                match digest_oid.to_string().as_str() {
                    ID_SHA256_DIGEST => verify_rsa::<sha2::Sha256>(&spki_der, message, signature)?,
                    ID_SHA384_DIGEST => verify_rsa::<sha2::Sha384>(&spki_der, message, signature)?,
                    ID_SHA512_DIGEST => verify_rsa::<sha2::Sha512>(&spki_der, message, signature)?,
                    other => {
                        return Err(format!(
                            "unsupported digestAlgorithm OID {other} for rsaEncryption signature"
                        ))
                    }
                }
            }
            // --- ECDSA: curve from SPKI, hash from the OID -----------------------
            // ecdsa-with-SHA256
            "1.2.840.10045.4.3.2" => {
                verify_ecdsa(&spki_der, &sha2::Sha256::digest(message), signature)?
            }
            // ecdsa-with-SHA384
            "1.2.840.10045.4.3.3" => {
                verify_ecdsa(&spki_der, &sha2::Sha384::digest(message), signature)?
            }
            // ecdsa-with-SHA512 (e.g. freeTSA: P-384 key, SHA-512 digest)
            "1.2.840.10045.4.3.4" => {
                verify_ecdsa(&spki_der, &sha2::Sha512::digest(message), signature)?
            }
            other => return Err(format!("unsupported signature algorithm OID {other}")),
        };
        if ok {
            Ok(())
        } else {
            Err("signature verification failed".to_string())
        }
    }

    /// RSA PKCS#1 v1.5 verify under a hash `D` (SHA-256/384/512). The hash must
    /// carry its DigestInfo OID (`AssociatedOid`), which is how PKCS#1 v1.5 names
    /// the hash in the padded block.
    fn verify_rsa<D>(spki_der: &[u8], message: &[u8], signature: &[u8]) -> Result<bool, String>
    where
        D: rsa::signature::digest::Digest + const_oid::AssociatedOid,
    {
        use rsa::pkcs1v15::{Signature as RsaSignature, VerifyingKey};
        use rsa::pkcs8::DecodePublicKey;
        use rsa::signature::Verifier;

        let sig = RsaSignature::try_from(signature)
            .map_err(|e| format!("signature is not a valid RSA signature: {e}"))?;
        let vk = VerifyingKey::<D>::from_public_key_der(spki_der)
            .map_err(|e| format!("public key is not RSA: {e}"))?;
        Ok(vk.verify(message, &sig).is_ok())
    }

    /// ECDSA verify over an explicit `prehash` (the already-computed message
    /// digest) and a DER-encoded signature (the X.509 / CMS form).
    ///
    /// The curve is taken from the SPKI: we try P-256 then P-384 (the curves in
    /// the dependency set). Verifying against an explicit prehash — rather than the
    /// curve verifier's built-in `Verifier`, which hardcodes the curve's default
    /// hash — lets the HASH be chosen by the signatureAlgorithm OID independently
    /// of the curve (so e.g. a P-384 key signed with SHA-512 verifies correctly).
    /// `bits2field` inside `verify_prehash` performs the RFC-6979 / X9.62 leftmost-
    /// bits truncation, so any digest length is handled per spec. A wrong key type
    /// or a malformed/invalid signature fails closed.
    fn verify_ecdsa(spki_der: &[u8], prehash: &[u8], signature: &[u8]) -> Result<bool, String> {
        // `signature` is not a direct dep of the lib (only a dev-dep); reach the
        // `PrehashVerifier` trait through `ecdsa`'s re-export, which is a `tsa` dep
        // and is the SAME `signature` crate instance p256/p384's keys implement.
        use ecdsa::signature::hazmat::PrehashVerifier;

        if let Ok(vk) = {
            use p256::pkcs8::DecodePublicKey;
            p256::ecdsa::VerifyingKey::from_public_key_der(spki_der)
        } {
            let sig = p256::ecdsa::DerSignature::try_from(signature)
                .map_err(|e| format!("signature is not a valid P-256 ECDSA signature: {e}"))?;
            return Ok(vk.verify_prehash(prehash, &sig).is_ok());
        }

        if let Ok(vk) = {
            use p384::pkcs8::DecodePublicKey;
            p384::ecdsa::VerifyingKey::from_public_key_der(spki_der)
        } {
            let sig = p384::ecdsa::DerSignature::try_from(signature)
                .map_err(|e| format!("signature is not a valid P-384 ECDSA signature: {e}"))?;
            return Ok(vk.verify_prehash(prehash, &sig).is_ok());
        }

        Err("ECDSA public key is neither P-256 nor P-384".to_string())
    }
}

// ============================================================================
// Producer (token requesting) — MINT-TIME network, feature `tsa-net` ONLY
// ============================================================================

/// With `tsa` but NOT `tsa-net`: there is no HTTP client linked, so minting a
/// fresh anchor is unavailable. This keeps the verify-only (`tsa`) build fully
/// offline (no ureq/reqwest/hyper). Callers that need to mint must build with
/// `tsa-net`.
#[cfg(all(feature = "tsa", not(feature = "tsa-net")))]
pub fn request_time_anchor(_action_hash: &str, _tsa_url: &str) -> Result<TimeAnchor, String> {
    Err("minting a time anchor requires the `tsa-net` feature (this build links no HTTP client)"
        .to_string())
}

/// Request an RFC-3161 timestamp token over `action_hash` from a TSA — the
/// PRODUCER side, compiled ONLY under `tsa-net` (the sole feature that links an
/// HTTP client; VERIFY never does).
///
/// The imprint is `SHA-256(the 32 raw BLAKE3 bytes of action_hash)` under the
/// `id-sha256` OID — no public RFC-3161 TSA signs a BLAKE3 imprint, and this
/// SHA-256 pre-image IS the authenticated `action_hash`, so it binds 1:1.
///
/// Flow: build a DER `TimeStampReq { version 1, messageImprint{id-sha256, sha256},
/// nonce (random u64), certReq=TRUE }`, POST it raw (`application/timestamp-query`,
/// 10s timeout, 64 KiB response cap), parse `TimeStampResp`, require `PKIStatus`
/// in {granted, grantedWithMods}, echo-check the nonce, extract the
/// `timeStampToken` (a CMS `ContentInfo`), and — VERIFY BEFORE ATTACH — run our
/// OWN offline verifier against [`PINNED_TSA_ROOTS`]. We never attach a token we
/// cannot ourselves prove.
#[cfg(feature = "tsa-net")]
pub fn request_time_anchor(action_hash: &str, tsa_url: &str) -> Result<TimeAnchor, String> {
    if !is_64_lower_hex(action_hash) {
        return Err("action_hash to anchor is not 64 lowercase-hex".to_string());
    }
    let nonce = tsa_net::random_nonce();
    let req_der = tsa_net::build_timestamp_req(action_hash, nonce)?;

    let token = tsa_net::post_and_extract_token(tsa_url, &req_der, nonce)?;

    let token_b64 = B64.encode(&token);
    let anchor = TimeAnchor {
        kind: TIME_ANCHOR_RFC3161.to_string(),
        token_b64,
        tsa: tsa_url.to_string(),
        anchored_hash: action_hash.to_string(),
    };

    // VERIFY BEFORE ATTACH: prove the freshly-minted token offline against the
    // pinned roots before we ever hand it back to be signed over.
    verify_time_anchor(&anchor, action_hash)
        .map_err(|e| format!("minted token failed our own offline verify (not attaching): {e}"))?;

    Ok(anchor)
}

/// The mint-time network + RFC-3161 request encoding, compiled ONLY under
/// `tsa-net`. Nothing here is reachable from the verify path.
#[cfg(feature = "tsa-net")]
mod tsa_net {
    use const_oid::ObjectIdentifier;
    use der::asn1::{Any, Int, OctetString};
    use der::{Decode, Encode, Reader, Sequence, SliceReader, Tag};
    use sha2::Digest;
    use x509_cert::spki::AlgorithmIdentifierOwned;

    const ID_SHA256_OID: ObjectIdentifier =
        ObjectIdentifier::new_unwrap("2.16.840.1.101.3.4.2.1");

    /// 64-hex → 32 raw bytes (local copy; the verifier's is private to its
    /// module). `None` if not exactly 64 hex chars.
    fn hex_to_32(s: &str) -> Option<[u8; 32]> {
        if s.len() != 64 {
            return None;
        }
        let mut out = [0u8; 32];
        let bytes = s.as_bytes();
        for (i, slot) in out.iter_mut().enumerate() {
            let hi = (bytes[2 * i] as char).to_digit(16)?;
            let lo = (bytes[2 * i + 1] as char).to_digit(16)?;
            *slot = (hi * 16 + lo) as u8;
        }
        Some(out)
    }

    /// Max response we will read from a TSA: 64 KiB. Tokens are a few KiB; this
    /// bounds a hostile/buggy server.
    const MAX_RESP: usize = 64 * 1024;

    /// `MessageImprint ::= SEQUENCE { hashAlgorithm AlgorithmIdentifier,
    /// hashedMessage OCTET STRING }`.
    #[derive(Sequence)]
    struct MessageImprint {
        hash_algorithm: AlgorithmIdentifierOwned,
        hashed_message: OctetString,
    }

    /// `TimeStampReq ::= SEQUENCE { version INTEGER (v1(1)),
    /// messageImprint MessageImprint, [reqPolicy omitted], nonce INTEGER OPTIONAL,
    /// certReq BOOLEAN DEFAULT FALSE, [extensions omitted] }`.
    ///
    /// We always send `certReq = TRUE` (load-bearing: without it both freeTSA and
    /// DigiCert strip the signer cert and the token is not offline-verifiable).
    /// `certReq` is DER DEFAULT FALSE, so encoding `true` is non-default and IS
    /// emitted.
    #[derive(Sequence)]
    struct TimeStampReq {
        version: i32,
        message_imprint: MessageImprint,
        nonce: Int,
        cert_req: bool,
    }

    /// A random non-zero u64 nonce. We use getrandom (already in the enterprise
    /// graph) rather than pulling a second rand_core major.
    pub fn random_nonce() -> u64 {
        let mut b = [0u8; 8];
        getrandom::getrandom(&mut b).expect("OS entropy for TSA nonce");
        // A zero nonce is legal but uninformative; bump it so the echo-check is
        // meaningful.
        let n = u64::from_le_bytes(b);
        if n == 0 {
            1
        } else {
            n
        }
    }

    /// Build the DER `TimeStampReq` over `SHA-256(raw action_hash bytes)`.
    pub fn build_timestamp_req(action_hash: &str, nonce: u64) -> Result<Vec<u8>, String> {
        let raw = hex_to_32(action_hash)
            .ok_or_else(|| "action_hash is not 64-hex (32 bytes)".to_string())?;
        let imprint = sha2::Sha256::digest(raw);

        let req = TimeStampReq {
            version: 1,
            message_imprint: MessageImprint {
                hash_algorithm: AlgorithmIdentifierOwned {
                    oid: ID_SHA256_OID,
                    parameters: None,
                },
                hashed_message: OctetString::new(imprint.to_vec())
                    .map_err(|e| format!("encode imprint octets: {e}"))?,
            },
            nonce: Int::new(&nonce.to_be_bytes())
                .map_err(|e| format!("encode nonce: {e}"))?,
            cert_req: true,
        };
        req.to_der().map_err(|e| format!("encode TimeStampReq: {e}"))
    }

    /// POST the DER request, enforce the response content-type/size, parse the
    /// `TimeStampResp`, check `PKIStatus`, echo-check `nonce`, and return the raw
    /// DER `timeStampToken` (a CMS `ContentInfo`).
    pub fn post_and_extract_token(
        tsa_url: &str,
        req_der: &[u8],
        nonce: u64,
    ) -> Result<Vec<u8>, String> {
        use std::io::Read;
        use std::time::Duration;

        let agent = ureq::AgentBuilder::new()
            .timeout(Duration::from_secs(10))
            .build();

        let resp = agent
            .post(tsa_url)
            .set("Content-Type", "application/timestamp-query")
            .send_bytes(req_der)
            .map_err(|e| format!("TSA POST failed: {e}"))?;

        if resp.status() != 200 {
            return Err(format!("TSA returned HTTP {}", resp.status()));
        }
        // RFC-3161 reply content-type (best-effort check; some servers vary case).
        let ctype = resp.header("Content-Type").unwrap_or_default().to_ascii_lowercase();
        if !ctype.contains("application/timestamp-reply") {
            return Err(format!("TSA reply has unexpected Content-Type `{ctype}`"));
        }

        let mut body = Vec::new();
        resp.into_reader()
            .take((MAX_RESP + 1) as u64)
            .read_to_end(&mut body)
            .map_err(|e| format!("reading TSA reply: {e}"))?;
        if body.len() > MAX_RESP {
            return Err("TSA reply exceeds 64 KiB cap; refusing".to_string());
        }

        extract_token(&body, nonce)
    }

    /// `PKIStatusInfo ::= SEQUENCE { status PKIStatus (INTEGER), ... }`.
    /// We only need `status`; trailing OPTIONAL fields are ignored by decoding
    /// just the leading INTEGER.
    #[derive(Sequence)]
    struct PkiStatusInfo {
        status: i32,
    }

    /// `TimeStampResp ::= SEQUENCE { status PKIStatusInfo,
    /// timeStampToken ContentInfo OPTIONAL }`.
    #[derive(Sequence)]
    struct TimeStampResp {
        status: PkiStatusInfo,
        // The token is a CMS ContentInfo; we capture it as Any to re-encode the
        // exact DER bytes (what we attach + verify).
        time_stamp_token: Option<Any>,
    }

    /// Parse the response, require a granted status, extract the token DER, and
    /// echo-check the nonce embedded in the token's TSTInfo.
    fn extract_token(resp_der: &[u8], nonce: u64) -> Result<Vec<u8>, String> {
        let resp = TimeStampResp::from_der(resp_der)
            .map_err(|e| format!("TimeStampResp is not valid DER: {e}"))?;

        // PKIStatus: granted(0) or grantedWithMods(1) are the only acceptable.
        match resp.status.status {
            0 | 1 => {}
            other => return Err(format!("TSA PKIStatus {other} is not granted; failing the mint")),
        }

        let token_any = resp
            .time_stamp_token
            .ok_or_else(|| "granted TimeStampResp carries no timeStampToken".to_string())?;
        let token_der = token_any
            .to_der()
            .map_err(|e| format!("re-encoding timeStampToken: {e}"))?;

        echo_check_nonce(&token_der, nonce)?;
        Ok(token_der)
    }

    /// Decode the token's TSTInfo far enough to read its `nonce` and confirm it
    /// equals the one we sent. A mismatch means a replay / wrong response — fail.
    fn echo_check_nonce(token_der: &[u8], nonce: u64) -> Result<(), String> {
        use cms::content_info::ContentInfo;
        use cms::signed_data::SignedData;

        let ci = ContentInfo::from_der(token_der)
            .map_err(|e| format!("minted token is not valid CMS: {e}"))?;
        let sd = ci
            .content
            .decode_as::<SignedData>()
            .map_err(|e| format!("minted token content is not SignedData: {e}"))?;
        let econtent = sd
            .encap_content_info
            .econtent
            .as_ref()
            .ok_or_else(|| "minted token has no eContent".to_string())?;
        let tst_der = econtent.value();

        // TSTInfo with the nonce field decoded. We re-declare a local shape that
        // reads through to the OPTIONAL nonce; fields after it are ignored.
        let got = read_tstinfo_nonce(tst_der)?;
        match got {
            Some(n) if n == nonce => Ok(()),
            Some(_) => Err("TSA token nonce does not echo the request nonce".to_string()),
            None => Err("TSA token carries no nonce to echo-check".to_string()),
        }
    }

    /// Pull the OPTIONAL `nonce INTEGER` out of a TSTInfo.
    ///
    /// After the five required fields, `TSTInfo` carries the OPTIONAL
    /// `accuracy` (SEQUENCE), `ordering` (BOOLEAN, DEFAULT FALSE), `nonce`
    /// (INTEGER), `[0] tsa` and `[1] extensions`. A `der::Sequence` derive over a
    /// fixed prefix + a single `Option<Int>` only works when the nonce is the very
    /// next field; real tokens interleave accuracy/ordering and append tsa/
    /// extensions, so that derive fails as "trailing data". We instead walk the
    /// SEQUENCE body by hand: skip the five required fields, then scan the trailing
    /// TLVs and take the first UNIVERSAL `INTEGER` as the nonce (accuracy is a
    /// SEQUENCE, ordering is BOOLEAN, and tsa/extensions are context-specific, so
    /// none of them collide with a bare INTEGER). Any malformed TLV is length-
    /// checked by the reader and fails closed.
    fn read_tstinfo_nonce(tst_der: &[u8]) -> Result<Option<u64>, String> {
        let map_err = |e: der::Error| format!("decoding TSTInfo for nonce echo failed: {e}");

        let mut outer = SliceReader::new(tst_der).map_err(map_err)?;
        let nonce_int: Option<Int> = outer
            .sequence(|body| {
                // version, policy, messageImprint, serialNumber, genTime — drained
                // by TLV framing; we trust none of them here, only the nonce.
                for _ in 0..5 {
                    body.tlv_bytes()?;
                }
                // Then OPTIONAL accuracy (SEQUENCE) / ordering (BOOLEAN) / nonce
                // (INTEGER) / [0] tsa / [1] extensions. The nonce is the first bare
                // UNIVERSAL INTEGER among them.
                let mut found: Option<Int> = None;
                while !body.is_finished() {
                    if found.is_none() && Tag::peek(body)? == Tag::Integer {
                        found = Some(Int::decode(body)?);
                    } else {
                        body.tlv_bytes()?;
                    }
                }
                Ok(found)
            })
            .map_err(map_err)?;

        match nonce_int {
            None => Ok(None),
            Some(int) => {
                let bytes = int.as_bytes();
                if bytes.len() > 8 {
                    return Err("TSA nonce wider than u64".to_string());
                }
                let mut buf = [0u8; 8];
                buf[8 - bytes.len()..].copy_from_slice(bytes);
                Ok(Some(u64::from_be_bytes(buf)))
            }
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn anchor(kind: &str, token_b64: &str, anchored_hash: &str) -> TimeAnchor {
        TimeAnchor {
            kind: kind.to_string(),
            token_b64: token_b64.to_string(),
            tsa: "https://tsa.example".to_string(),
            anchored_hash: anchored_hash.to_string(),
        }
    }

    /// Decode a 64-char hex string into 32 raw bytes (shared with the `tsa`
    /// crypto tests, which mint a token's messageImprint over these bytes).
    #[cfg(feature = "tsa")]
    pub(super) fn hex32(s: &str) -> [u8; 32] {
        assert_eq!(s.len(), 64, "expected 64 hex chars");
        let mut out = [0u8; 32];
        for (i, slot) in out.iter_mut().enumerate() {
            *slot = u8::from_str_radix(&s[2 * i..2 * i + 2], 16).expect("hex");
        }
        out
    }

    /// Under the `tsa` feature the build.rs-generated pin set must carry the real
    /// roots (DigiCert G4, DigiCert Assured ID, freeTSA) to chain to.
    #[cfg(feature = "tsa")]
    #[test]
    fn pinned_roots_are_configured() {
        assert!(pinned_root_count() >= 2, "expected >=2 pinned roots, got {}", pinned_root_count());
    }

    /// Without the `tsa` feature there is no verifier crypto stack, so the pin set
    /// is empty by construction — a present anchor fails closed for lack of a
    /// crypto path, not for lack of roots.
    #[cfg(not(feature = "tsa"))]
    #[test]
    fn no_pinned_roots_without_feature() {
        assert_eq!(pinned_root_count(), 0);
    }

    #[test]
    fn wrong_kind_fails_closed() {
        let h = "a".repeat(64);
        let a = anchor("roughtime", "AAAA", &h);
        let err = verify_time_anchor(&a, &h).unwrap_err();
        assert!(err.contains("not supported"), "got: {err}");
    }

    #[test]
    fn non_hex_anchored_hash_fails_closed() {
        let a = anchor(TIME_ANCHOR_RFC3161, "AAAA", "NOTHEX");
        let err = verify_time_anchor(&a, "NOTHEX").unwrap_err();
        assert!(err.contains("64 lowercase-hex"), "got: {err}");
    }

    #[test]
    fn anchored_hash_mismatch_fails_closed() {
        let h = "a".repeat(64);
        let other = "b".repeat(64);
        let a = anchor(TIME_ANCHOR_RFC3161, "AAAA", &h);
        let err = verify_time_anchor(&a, &other).unwrap_err();
        assert!(err.contains("does not match action_hash"), "got: {err}");
    }

    #[test]
    fn bad_base64_token_fails_closed() {
        let h = "a".repeat(64);
        let a = anchor(TIME_ANCHOR_RFC3161, "not base64!!!", &h);
        let err = verify_time_anchor(&a, &h).unwrap_err();
        assert!(err.contains("not valid base64"), "got: {err}");
    }

    /// With the `tsa` feature OFF (the default test build), a present anchor that
    /// passes every precondition STILL fails closed — the build cannot do the
    /// crypto, so it must not vouch for the time.
    #[cfg(not(feature = "tsa"))]
    #[test]
    fn precondition_passing_anchor_fails_closed_without_feature() {
        let h = "a".repeat(64);
        // A valid-base64, non-empty token over the right hash and kind.
        let a = anchor(TIME_ANCHOR_RFC3161, "QUJDRA==", &h);
        let err = verify_time_anchor(&a, &h).unwrap_err();
        assert!(err.contains("unavailable in this build"), "got: {err}");
    }
}

// ============================================================================
// TSA crypto end-to-end tests (feature `tsa`)
// ============================================================================
//
// These mint a THROWAWAY RSA root + TSA-signer hierarchy and a real RFC-3161
// token at test time (no fixture bytes are checked in), then exercise the full
// verify path — messageImprint match + BLAKE3 imprint-OID pin + timeStamping EKU
// + chain-to-the-test-root + RSA SignerInfo signature — by passing the generated
// root DER directly into `tsa_crypto::verify` (the production pin set is never
// touched). A wrong/forged token must fail closed.

#[cfg(all(test, feature = "tsa"))]
mod tsa_crypto_tests {
    use super::tsa_crypto;

    use cms::cert::CertificateChoices;
    use cms::content_info::{CmsVersion, ContentInfo};
    use cms::signed_data::{
        CertificateSet, EncapsulatedContentInfo, SignedData, SignerIdentifier, SignerInfo,
        SignerInfos,
    };
    use const_oid::db::rfc5280::ID_KP_TIME_STAMPING;
    use const_oid::ObjectIdentifier;
    use der::asn1::{Any, GeneralizedTime, Int, OctetString, SetOfVec};
    use der::{Encode, Sequence, Tag};
    use rsa::pkcs1v15::{Signature as RsaSignature, SigningKey};
    use rsa::RsaPrivateKey;
    use sha2::{Digest, Sha256};
    use signature::{SignatureEncoding, Signer};
    use std::str::FromStr;
    use std::time::Duration;
    use x509_cert::attr::Attribute;
    use x509_cert::builder::profile::BuilderProfile;
    use x509_cert::builder::{Builder, CertificateBuilder};
    use x509_cert::certificate::TbsCertificate;
    use x509_cert::ext::pkix::ExtendedKeyUsage;
    use x509_cert::ext::Extension;
    use x509_cert::name::Name;
    use x509_cert::serial_number::SerialNumber;
    use x509_cert::spki::{
        AlgorithmIdentifierOwned, SubjectPublicKeyInfoOwned, SubjectPublicKeyInfoRef,
    };
    use x509_cert::time::Validity;
    use x509_cert::Certificate;

    const ID_CT_TST_INFO: ObjectIdentifier =
        ObjectIdentifier::new_unwrap("1.2.840.113549.1.9.16.1.4");
    const ID_SHA256: ObjectIdentifier = ObjectIdentifier::new_unwrap("2.16.840.1.101.3.4.2.1");
    const ID_SHA256_WITH_RSA: ObjectIdentifier =
        ObjectIdentifier::new_unwrap("1.2.840.113549.1.1.11");
    /// id-contentType (PKCS#9).
    const ID_CONTENT_TYPE: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113549.1.9.3");
    /// id-messageDigest (PKCS#9).
    const ID_MESSAGE_DIGEST: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113549.1.9.4");
    const BLAKE3_OID: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.3.6.1.4.1.1722.12.2.1");

    // --- The same minimal TSTInfo/MessageImprint shapes the verifier decodes. ---
    #[derive(Clone, Debug, Eq, PartialEq, Sequence)]
    struct MessageImprint {
        hash_algorithm: AlgorithmIdentifierOwned,
        hashed_message: OctetString,
    }
    #[derive(Clone, Debug, Eq, PartialEq, Sequence)]
    struct TstInfo {
        version: i32,
        policy: ObjectIdentifier,
        message_imprint: MessageImprint,
        serial_number: Int,
        gen_time: GeneralizedTime,
    }

    /// A profile that emits NO extensions and reports a fixed subject/issuer — we
    /// add the EKU ourselves via `add_extension`. `get_issuer` returns the configured
    /// issuer name so a leaf is issued by the root's subject.
    struct PlainProfile {
        subject: Name,
        issuer: Name,
    }
    impl BuilderProfile for PlainProfile {
        fn get_issuer(&self, _subject: &Name) -> Name {
            self.issuer.clone()
        }
        fn get_subject(&self) -> Name {
            self.subject.clone()
        }
        fn build_extensions(
            &self,
            _spk: SubjectPublicKeyInfoRef<'_>,
            _issuer_spk: SubjectPublicKeyInfoRef<'_>,
            _tbs: &TbsCertificate,
        ) -> x509_cert::builder::Result<Vec<Extension>> {
            Ok(Vec::new())
        }
    }

    fn cn(common_name: &str) -> Name {
        Name::from_str(&format!("CN={common_name}")).expect("parse CN name")
    }

    /// The fixed token genTime the test tokens assert (seconds since Unix epoch).
    /// The verifier now windows cert validity against THIS instant (offline,
    /// deterministic), so the test certs must be valid around it.
    const TEST_GEN_TIME_SECS: u64 = 1_780_660_800;

    /// A validity window that brackets [`TEST_GEN_TIME_SECS`] by ±1 year, so the
    /// token's genTime lands inside every cert on the test path regardless of the
    /// wall-clock at test time (the verifier never reads wall-clock).
    fn validity_around_gen_time() -> Validity {
        const YEAR: u64 = 365 * 24 * 3600;
        let nb = GeneralizedTime::from_unix_duration(Duration::from_secs(TEST_GEN_TIME_SECS - YEAR))
            .expect("notBefore");
        let na = GeneralizedTime::from_unix_duration(Duration::from_secs(TEST_GEN_TIME_SECS + YEAR))
            .expect("notAfter");
        Validity::new(
            x509_cert::time::Time::GeneralTime(nb),
            x509_cert::time::Time::GeneralTime(na),
        )
    }

    /// A deterministic BLAKE3-XOF-backed CryptoRng — no OS entropy, no network, so
    /// the test hierarchy is reproducible. (A real TSA uses OS entropy; this is a
    /// throwaway TEST key, and determinism keeps the suite hermetic.)
    struct XofRng {
        reader: blake3::OutputReader,
    }
    impl XofRng {
        fn seeded(seed: &[u8]) -> Self {
            let mut h = blake3::Hasher::new();
            h.update(seed);
            Self { reader: h.finalize_xof() }
        }
    }
    impl rand_core::TryRng for XofRng {
        type Error = core::convert::Infallible;
        fn try_next_u32(&mut self) -> Result<u32, Self::Error> {
            let mut b = [0u8; 4];
            self.reader.fill(&mut b);
            Ok(u32::from_le_bytes(b))
        }
        fn try_next_u64(&mut self) -> Result<u64, Self::Error> {
            let mut b = [0u8; 8];
            self.reader.fill(&mut b);
            Ok(u64::from_le_bytes(b))
        }
        fn try_fill_bytes(&mut self, dst: &mut [u8]) -> Result<(), Self::Error> {
            self.reader.fill(dst);
            Ok(())
        }
    }
    impl rand_core::TryCryptoRng for XofRng {}

    /// Generate a 2048-bit RSA key from a seeded RNG (a real TSA key size).
    fn rsa_key(seed: &[u8]) -> SigningKey<Sha256> {
        let mut rng = XofRng::seeded(seed);
        let priv_key = RsaPrivateKey::new(&mut rng, 2048).expect("generate RSA key");
        SigningKey::<Sha256>::new(priv_key)
    }

    fn spki_of(signing: &SigningKey<Sha256>) -> SubjectPublicKeyInfoOwned {
        use rsa::pkcs8::EncodePublicKey;
        use signature::Keypair;
        let vk = signing.verifying_key();
        let der = vk.to_public_key_der().expect("encode SPKI").into_vec();
        SubjectPublicKeyInfoOwned::try_from(der.as_slice()).expect("parse SPKI")
    }

    /// A self-signed root certificate.
    fn make_root(signing: &SigningKey<Sha256>, name: &Name) -> Certificate {
        let profile = PlainProfile { subject: name.clone(), issuer: name.clone() };
        let builder = CertificateBuilder::new(
            profile,
            SerialNumber::from(1u32),
            validity_around_gen_time(),
            spki_of(signing),
        )
        .expect("root builder");
        builder.build::<_, RsaSignature>(signing).expect("build root")
    }

    /// A TSA signer cert issued by `root` (issuer = root subject), carrying the
    /// `id-kp-timeStamping` EKU, signed by `root_signing`.
    fn make_tsa_signer(
        root: &Certificate,
        root_signing: &SigningKey<Sha256>,
        signer_signing: &SigningKey<Sha256>,
        subject: &Name,
        add_eku: bool,
    ) -> Certificate {
        let profile = PlainProfile {
            subject: subject.clone(),
            issuer: root.tbs_certificate().subject().clone(),
        };
        let mut builder = CertificateBuilder::new(
            profile,
            SerialNumber::from(2u32),
            validity_around_gen_time(),
            spki_of(signer_signing),
        )
        .expect("leaf builder");
        if add_eku {
            builder
                .add_extension(&ExtendedKeyUsage(vec![ID_KP_TIME_STAMPING]))
                .expect("add EKU");
        }
        builder.build::<_, RsaSignature>(root_signing).expect("build leaf")
    }

    /// DER-encode a TSTInfo over `digest` under `imprint_oid` at the fixed test
    /// genTime.
    fn tst_info_der(digest: &[u8], imprint_oid: ObjectIdentifier) -> Vec<u8> {
        tst_info_der_at(digest, imprint_oid, TEST_GEN_TIME_SECS)
    }

    /// As [`tst_info_der`] but at an explicit genTime (to exercise the
    /// cert-validity-window check against the token's own time).
    fn tst_info_der_at(digest: &[u8], imprint_oid: ObjectIdentifier, gen_secs: u64) -> Vec<u8> {
        let tst = TstInfo {
            version: 1,
            policy: ObjectIdentifier::new_unwrap("1.2.3.4.1"),
            message_imprint: MessageImprint {
                hash_algorithm: AlgorithmIdentifierOwned { oid: imprint_oid, parameters: None },
                hashed_message: OctetString::new(digest.to_vec()).unwrap(),
            },
            serial_number: Int::new(&[0x2a]).unwrap(),
            gen_time: GeneralizedTime::from_unix_duration(Duration::from_secs(gen_secs)).unwrap(),
        };
        tst.to_der().expect("encode TstInfo")
    }

    /// Build one signed attribute `{ oid, values: SET { value } }`.
    fn attr(oid: ObjectIdentifier, value: Any) -> Attribute {
        let mut set = SetOfVec::new();
        set.insert(value).unwrap();
        Attribute { oid, values: set }
    }

    /// Mint a full RFC-3161 token embedding just the signer cert.
    fn mint_token(
        tst_der: &[u8],
        signer_cert: &Certificate,
        signer_signing: &SigningKey<Sha256>,
    ) -> Vec<u8> {
        mint_token_with_certs(tst_der, signer_cert, &[signer_cert], signer_signing)
    }

    /// Mint a full RFC-3161 token (CMS ContentInfo DER) over `tst_der`, signed by
    /// `signer_signing`, with the SignerInfo `sid` bound to `signer_cert` and
    /// `embed_certs` placed in the SignedData certificate set (so a multi-hop
    /// chain can be carried). Built by hand (no cms builder): the SignerInfo
    /// carries the content-type + message-digest signed attrs and the RSA-SHA256
    /// signature over their DER (RFC 5652 §5.4).
    fn mint_token_with_certs(
        tst_der: &[u8],
        signer_cert: &Certificate,
        embed_certs: &[&Certificate],
        signer_signing: &SigningKey<Sha256>,
    ) -> Vec<u8> {
        let econtent = EncapsulatedContentInfo {
            econtent_type: ID_CT_TST_INFO,
            econtent: Some(Any::new(Tag::OctetString, tst_der).unwrap()),
        };
        let digest_alg = AlgorithmIdentifierOwned { oid: ID_SHA256, parameters: None };

        // Signed attributes: content-type (id-ct-TSTInfo) + message-digest(eContent).
        let md = Sha256::digest(tst_der);
        let content_type_attr = attr(
            ID_CONTENT_TYPE,
            Any::encode_from(&ID_CT_TST_INFO).expect("encode content-type oid"),
        );
        let message_digest_attr = attr(
            ID_MESSAGE_DIGEST,
            Any::new(Tag::OctetString, md.as_slice()).unwrap(),
        );
        let mut signed_attrs: SetOfVec<Attribute> = SetOfVec::new();
        signed_attrs.insert(content_type_attr).unwrap();
        signed_attrs.insert(message_digest_attr).unwrap();

        // RFC 5652 §5.4: the signature is over the DER of the SignedAttributes
        // re-tagged as a SET OF (which `SetOfVec::to_der` produces).
        let signed_attrs_der = signed_attrs.to_der().expect("encode signed attrs");
        let rsa_sig: RsaSignature = signer_signing.sign(&signed_attrs_der);

        let signer_info = SignerInfo {
            version: CmsVersion::V1,
            sid: SignerIdentifier::from(signer_cert),
            digest_alg,
            signed_attrs: Some(signed_attrs),
            signature_algorithm: AlgorithmIdentifierOwned {
                oid: ID_SHA256_WITH_RSA,
                parameters: None,
            },
            signature: OctetString::new(rsa_sig.to_vec()).unwrap(),
            unsigned_attrs: None,
        };

        let mut digest_algs: SetOfVec<AlgorithmIdentifierOwned> = SetOfVec::new();
        digest_algs
            .insert(AlgorithmIdentifierOwned { oid: ID_SHA256, parameters: None })
            .unwrap();
        let mut signer_infos_set: SetOfVec<SignerInfo> = SetOfVec::new();
        signer_infos_set.insert(signer_info).unwrap();
        let mut certs_set: SetOfVec<CertificateChoices> = SetOfVec::new();
        for c in embed_certs {
            certs_set.insert(CertificateChoices::Certificate((*c).clone())).unwrap();
        }

        let signed_data = SignedData {
            version: CmsVersion::V3,
            digest_algorithms: digest_algs,
            encap_content_info: econtent,
            certificates: Some(CertificateSet(certs_set)),
            crls: None,
            signer_infos: SignerInfos(signer_infos_set),
        };

        // Wrap as ContentInfo { contentType = id-signedData, content = SignedData }.
        let ci = ContentInfo {
            content_type: const_oid::db::rfc5911::ID_SIGNED_DATA,
            content: Any::encode_from(&signed_data).expect("encode SignedData into Any"),
        };
        ci.to_der().expect("encode ContentInfo")
    }

    // --- ECDSA P-256 hierarchy ------------------------------------------------
    //
    // DigiCert's *Trusted Root G4* path is RSA today, but RFC-3161 responders
    // CAN be ECDSA, and the verifier's `verify_ecdsa_p256`/`_p384` dispatch
    // (tsa.rs) must be proven to actually accept a real P-256 signature — not
    // merely to compile. These helpers mint a throwaway ECDSA P-256 root + TSA
    // signer and an RFC-3161 token whose cert-chain hops AND CMS SignerInfo are
    // both `ecdsa-with-SHA256`, so the whole ECDSA path is exercised end-to-end.

    /// `ecdsa-with-SHA256` (1.2.840.10045.4.3.2) — the P-256 signature OID the
    /// verifier dispatches to `verify_ecdsa_p256` on.
    const ECDSA_WITH_SHA256: ObjectIdentifier =
        ObjectIdentifier::new_unwrap("1.2.840.10045.4.3.2");

    /// Generate a deterministic P-256 ECDSA signing key from a seeded RNG (no OS
    /// entropy / network — the suite stays hermetic and reproducible).
    fn p256_key(seed: &[u8]) -> p256::ecdsa::SigningKey {
        use p256::elliptic_curve::Generate;
        let mut rng = XofRng::seeded(seed);
        p256::ecdsa::SigningKey::generate_from_rng(&mut rng)
    }

    fn p256_spki(signing: &p256::ecdsa::SigningKey) -> SubjectPublicKeyInfoOwned {
        use p256::pkcs8::EncodePublicKey;
        let der = signing
            .verifying_key()
            .to_public_key_der()
            .expect("encode P-256 SPKI")
            .into_vec();
        SubjectPublicKeyInfoOwned::try_from(der.as_slice()).expect("parse P-256 SPKI")
    }

    /// A self-signed P-256 ECDSA root certificate.
    fn make_p256_root(signing: &p256::ecdsa::SigningKey, name: &Name) -> Certificate {
        let profile = PlainProfile { subject: name.clone(), issuer: name.clone() };
        let builder = CertificateBuilder::new(
            profile,
            SerialNumber::from(1u32),
            validity_around_gen_time(),
            p256_spki(signing),
        )
        .expect("p256 root builder");
        builder
            .build::<_, p256::ecdsa::DerSignature>(signing)
            .expect("build p256 root")
    }

    /// A P-256 TSA signer cert issued by `root` (issuer = root subject), carrying
    /// the `id-kp-timeStamping` EKU, ECDSA-signed by `root_signing`.
    fn make_p256_tsa_signer(
        root: &Certificate,
        root_signing: &p256::ecdsa::SigningKey,
        signer_signing: &p256::ecdsa::SigningKey,
        subject: &Name,
    ) -> Certificate {
        let profile = PlainProfile {
            subject: subject.clone(),
            issuer: root.tbs_certificate().subject().clone(),
        };
        let mut builder = CertificateBuilder::new(
            profile,
            SerialNumber::from(2u32),
            validity_around_gen_time(),
            p256_spki(signer_signing),
        )
        .expect("p256 leaf builder");
        builder
            .add_extension(&ExtendedKeyUsage(vec![ID_KP_TIME_STAMPING]))
            .expect("add EKU");
        builder
            .build::<_, p256::ecdsa::DerSignature>(root_signing)
            .expect("build p256 leaf")
    }

    /// Mint an RFC-3161 token whose CMS SignerInfo signature is `ecdsa-with-SHA256`
    /// (P-256), built by hand exactly like [`mint_token_with_certs`] but signing
    /// the SignedAttributes DER with a P-256 key and stamping the ECDSA OID.
    fn mint_token_ecdsa(
        tst_der: &[u8],
        signer_cert: &Certificate,
        embed_certs: &[&Certificate],
        signer_signing: &p256::ecdsa::SigningKey,
    ) -> Vec<u8> {
        use p256::ecdsa::signature::Signer as _;

        let econtent = EncapsulatedContentInfo {
            econtent_type: ID_CT_TST_INFO,
            econtent: Some(Any::new(Tag::OctetString, tst_der).unwrap()),
        };
        let digest_alg = AlgorithmIdentifierOwned { oid: ID_SHA256, parameters: None };

        let md = Sha256::digest(tst_der);
        let content_type_attr = attr(
            ID_CONTENT_TYPE,
            Any::encode_from(&ID_CT_TST_INFO).expect("encode content-type oid"),
        );
        let message_digest_attr =
            attr(ID_MESSAGE_DIGEST, Any::new(Tag::OctetString, md.as_slice()).unwrap());
        let mut signed_attrs: SetOfVec<Attribute> = SetOfVec::new();
        signed_attrs.insert(content_type_attr).unwrap();
        signed_attrs.insert(message_digest_attr).unwrap();

        let signed_attrs_der = signed_attrs.to_der().expect("encode signed attrs");
        // DER ECDSA signature — the X.509/CMS form `verify_ecdsa_p256` parses.
        let ecdsa_sig: p256::ecdsa::DerSignature = signer_signing.sign(&signed_attrs_der);

        let signer_info = SignerInfo {
            version: CmsVersion::V1,
            sid: SignerIdentifier::from(signer_cert),
            digest_alg,
            signed_attrs: Some(signed_attrs),
            signature_algorithm: AlgorithmIdentifierOwned {
                oid: ECDSA_WITH_SHA256,
                parameters: None,
            },
            signature: OctetString::new(ecdsa_sig.as_bytes().to_vec()).unwrap(),
            unsigned_attrs: None,
        };

        let mut digest_algs: SetOfVec<AlgorithmIdentifierOwned> = SetOfVec::new();
        digest_algs
            .insert(AlgorithmIdentifierOwned { oid: ID_SHA256, parameters: None })
            .unwrap();
        let mut signer_infos_set: SetOfVec<SignerInfo> = SetOfVec::new();
        signer_infos_set.insert(signer_info).unwrap();
        let mut certs_set: SetOfVec<CertificateChoices> = SetOfVec::new();
        for c in embed_certs {
            certs_set.insert(CertificateChoices::Certificate((*c).clone())).unwrap();
        }

        let signed_data = SignedData {
            version: CmsVersion::V3,
            digest_algorithms: digest_algs,
            encap_content_info: econtent,
            certificates: Some(CertificateSet(certs_set)),
            crls: None,
            signer_infos: SignerInfos(signer_infos_set),
        };

        let ci = ContentInfo {
            content_type: const_oid::db::rfc5911::ID_SIGNED_DATA,
            content: Any::encode_from(&signed_data).expect("encode SignedData into Any"),
        };
        ci.to_der().expect("encode ContentInfo")
    }

    /// A full ECDSA P-256 fixture: ECDSA root -> ECDSA TSA signer, and a token
    /// whose chain hops + SignerInfo are all `ecdsa-with-SHA256`. Returns
    /// (token_der, root_der).
    fn fixture_ecdsa_p256(hash_hex: &str) -> (Vec<u8>, Vec<u8>) {
        let root_signing = p256_key(b"heso-test-ecdsa-root");
        let signer_signing = p256_key(b"heso-test-ecdsa-signer");
        let root = make_p256_root(&root_signing, &cn("HESO ECDSA Root"));
        let signer =
            make_p256_tsa_signer(&root, &root_signing, &signer_signing, &cn("HESO ECDSA TSA"));

        let tst = tst_info_der(&sha256_imprint(hash_hex), ID_SHA256);
        let token = mint_token_ecdsa(&tst, &signer, &[&signer], &signer_signing);
        let root_der = root.to_der().unwrap();
        (token, root_der)
    }

    /// The verifier-correct imprint: `SHA-256(the 32 raw BLAKE3 action_hash
    /// bytes)`. This is what a real TSA signs and what `check_message_imprint`
    /// recomputes.
    fn sha256_imprint(hash_hex: &str) -> Vec<u8> {
        let raw = super::tests::hex32(hash_hex);
        Sha256::digest(raw).to_vec()
    }

    /// Standard fixture: a fresh RSA hierarchy + a token whose messageImprint is
    /// `SHA-256(action_hash bytes)` under `id-sha256`. Returns (token_der, root_der).
    fn fixture(hash_hex: &str, add_eku: bool) -> (Vec<u8>, Vec<u8>) {
        fixture_with_imprint(hash_hex, ID_SHA256, &sha256_imprint(hash_hex), add_eku)
    }

    /// Like [`fixture`] but lets a test override the imprint OID and/or the
    /// imprint bytes (to exercise wrong-algorithm / wrong-hash fail-closed paths).
    fn fixture_with_imprint(
        _hash_hex: &str,
        imprint_oid: ObjectIdentifier,
        imprint: &[u8],
        add_eku: bool,
    ) -> (Vec<u8>, Vec<u8>) {
        let root_signing = rsa_key(b"heso-test-tsa-root");
        let signer_signing = rsa_key(b"heso-test-tsa-signer");
        let root = make_root(&root_signing, &cn("HESO Test TSA Root"));
        let signer =
            make_tsa_signer(&root, &root_signing, &signer_signing, &cn("HESO Test TSA"), add_eku);

        let tst = tst_info_der(imprint, imprint_oid);
        let token = mint_token(&tst, &signer, &signer_signing);
        let root_der = root.to_der().unwrap();
        (token, root_der)
    }

    /// A 2-hop fixture: leaf signer -> embedded intermediate -> pinned root. Proves
    /// the bounded path builder walks more than one level. Returns
    /// (token_der, root_der) where the token embeds BOTH the signer and the
    /// intermediate, and `root` is the pinned anchor.
    fn fixture_with_intermediate(hash_hex: &str) -> (Vec<u8>, Vec<u8>) {
        let root_signing = rsa_key(b"heso-test-2hop-root");
        let inter_signing = rsa_key(b"heso-test-2hop-inter");
        let signer_signing = rsa_key(b"heso-test-2hop-signer");

        let root = make_root(&root_signing, &cn("HESO 2hop Root"));
        // Intermediate is issued by root (issuer = root subject), signed by root.
        let intermediate = make_tsa_signer(
            &root,
            &root_signing,
            &inter_signing,
            &cn("HESO 2hop Intermediate"),
            false,
        );
        // Leaf signer is issued by the intermediate, carries the timeStamping EKU.
        let signer = make_tsa_signer(
            &intermediate,
            &inter_signing,
            &signer_signing,
            &cn("HESO 2hop TSA"),
            true,
        );

        let tst = tst_info_der(&sha256_imprint(hash_hex), ID_SHA256);
        let token = mint_token_with_certs(&tst, &signer, &[&signer, &intermediate], &signer_signing);
        let root_der = root.to_der().unwrap();
        (token, root_der)
    }

    fn action_hash() -> String {
        blake3::hash(b"the action being anchored").to_hex().to_string()
    }

    #[test]
    fn valid_token_over_correct_hash_verifies() {
        let h = action_hash();
        let (token, root_der) = fixture(&h, true);
        let gen_time = tsa_crypto::verify(&token, &h, &[root_der.as_slice()])
            .expect("a well-formed token over the right hash must verify");
        assert!(gen_time.contains("2026"), "genTime should be returned: {gen_time}");
    }

    /// The bounded path builder must walk leaf -> intermediate -> pinned root.
    #[test]
    fn two_hop_chain_to_pinned_root_verifies() {
        let h = action_hash();
        let (token, root_der) = fixture_with_intermediate(&h);
        let gen_time = tsa_crypto::verify(&token, &h, &[root_der.as_slice()])
            .expect("a 2-hop chain to the pinned root must verify");
        assert!(gen_time.contains("2026"), "genTime should be returned: {gen_time}");
    }

    /// An ECDSA P-256 token (root + signer + SignerInfo all `ecdsa-with-SHA256`)
    /// must verify — proving `verify_ecdsa_p256` accepts a REAL P-256 signature on
    /// both the cert-chain hop and the CMS SignerInfo, not merely that it compiles.
    #[test]
    fn ecdsa_p256_token_verifies() {
        let h = action_hash();
        let (token, root_der) = fixture_ecdsa_p256(&h);
        let gen_time = tsa_crypto::verify(&token, &h, &[root_der.as_slice()])
            .expect("an ECDSA P-256 token over the right hash must verify");
        assert!(gen_time.contains("2026"), "genTime should be returned: {gen_time}");
    }

    /// Tampering an ECDSA P-256 token's signature region must fail closed — the
    /// ECDSA verify path rejects a broken P-256 signature just like the RSA one.
    #[test]
    fn ecdsa_p256_tampered_signature_fails_closed() {
        let h = action_hash();
        let (mut token, root_der) = fixture_ecdsa_p256(&h);
        let last = token.len() - 1;
        token[last] ^= 0x01;
        let err = tsa_crypto::verify(&token, &h, &[root_der.as_slice()]);
        assert!(err.is_err(), "a tampered ECDSA token must fail closed, got {err:?}");
    }

    #[test]
    fn message_imprint_mismatch_fails_closed() {
        // Mint the token over a DIFFERENT hash than the one we verify against.
        let other = blake3::hash(b"a different action").to_hex().to_string();
        let (token, root_der) = fixture(&other, true);
        let err = tsa_crypto::verify(&token, &action_hash(), &[root_der.as_slice()]).unwrap_err();
        assert!(err.contains("hashedMessage does not equal"), "got: {err}");
    }

    #[test]
    fn wrong_imprint_algorithm_fails_closed() {
        let h = action_hash();
        // A token whose imprint claims the BLAKE3 OID (not the pinned id-sha256).
        let (token, root_der) =
            fixture_with_imprint(&h, BLAKE3_OID, &super::tests::hex32(&h), true);
        let err = tsa_crypto::verify(&token, &h, &[root_der.as_slice()]).unwrap_err();
        assert!(err.contains("not the expected id-sha256 OID"), "got: {err}");
    }

    #[test]
    fn signer_not_chained_to_pinned_root_fails_closed() {
        let h = action_hash();
        let (token, _root_der) = fixture(&h, true);
        // Verify against a DIFFERENT, unrelated root.
        let other_signing = rsa_key(b"heso-test-unrelated-root");
        let other_root = make_root(&other_signing, &cn("Unrelated Root"));
        let other_der = other_root.to_der().unwrap();
        let err = tsa_crypto::verify(&token, &h, &[other_der.as_slice()]).unwrap_err();
        assert!(err.contains("does not reach any pinned root"), "got: {err}");
    }

    #[test]
    fn tampered_signature_fails_closed() {
        let h = action_hash();
        let (mut token, root_der) = fixture(&h, true);
        // Flip a late byte (inside the SignerInfo signature region) — the token is
        // still well-formed CMS but the RSA signature no longer verifies.
        let last = token.len() - 1;
        token[last] ^= 0x01;
        let err = tsa_crypto::verify(&token, &h, &[root_der.as_slice()]);
        assert!(err.is_err(), "a tampered token must fail closed, got {err:?}");
    }

    #[test]
    fn missing_timestamping_eku_fails_closed() {
        let h = action_hash();
        // Mint the signer WITHOUT the timeStamping EKU.
        let (token, root_der) = fixture(&h, false);
        let err = tsa_crypto::verify(&token, &h, &[root_der.as_slice()]).unwrap_err();
        // A signer with no timeStamping EKU fails closed — either because it
        // carries no EKU extension at all, or because the EKU lacks the OID.
        assert!(
            err.contains("EKU")
                || err.contains("Extended Key Usage")
                || err.contains("no extensions")
                || err.contains("id-kp-timeStamping"),
            "got: {err}"
        );
    }

    /// A token whose genTime falls OUTSIDE the signer cert's validity window must
    /// fail closed — proving the offline notBefore<=genTime<=notAfter check using
    /// the token's own genTime (never wall-clock).
    #[test]
    fn gen_time_outside_cert_window_fails_closed() {
        let h = action_hash();
        // Build certs valid around TEST_GEN_TIME_SECS but a TSTInfo whose genTime is
        // ~3 years later (outside the ±1y window).
        let root_signing = rsa_key(b"heso-test-window-root");
        let signer_signing = rsa_key(b"heso-test-window-signer");
        let root = make_root(&root_signing, &cn("HESO Window Root"));
        let signer = make_tsa_signer(
            &root,
            &root_signing,
            &signer_signing,
            &cn("HESO Window TSA"),
            true,
        );
        let tst = tst_info_der_at(
            &sha256_imprint(&h),
            ID_SHA256,
            TEST_GEN_TIME_SECS + 3 * 365 * 24 * 3600,
        );
        let token = mint_token(&tst, &signer, &signer_signing);
        let root_der = root.to_der().unwrap();
        let err = tsa_crypto::verify(&token, &h, &[root_der.as_slice()]).unwrap_err();
        assert!(
            err.contains("expired at the token genTime")
                || err.contains("not yet valid at the token genTime"),
            "got: {err}"
        );
    }
}
